services:
    web:
        build:
            context: ./
            dockerfile: ./.docker/php/Dockerfile.local
        ports:
            - ${APP_PORT:-8000}:8000
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes:
            - ./:${WORKDIR}
            - ./vendor/:${WORKDIR}/vendor
        networks:
            - crm-network
        depends_on:
            - mysql
            - redis
    roadrunner:
        build:
          context: ./
          dockerfile: ./.docker/php/Dockerfile-roadrunner.local
        ports:
          - ${APP_PORT_RR:-8081}:8081
          - ${VITE_PORT_RR:-5173}:${VITE_PORT:-5173}
        volumes:
          - ./:${WORKDIR}
          - ./vendor/:${WORKDIR}/vendor
        networks:
          - crm-network
        depends_on:
          - mysql
          - redis

    mysql:
        image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
        ports:
            - ${FORWARD_DB_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ${DB_VOLUME_LOCAL:-./database/mysql-test-data}:/var/lib/mysql
        networks:
            - crm-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -p${DB_PASSWORD}
            retries: 3
            timeout: 5s
    redis:
        image: redis:alpine
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
        volumes:
            - ${REDIS_VOLUME_LOCAL:-./database/redis-data}:/data
        networks:
            - crm-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    crm-network:
        driver: bridge
